In [4]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [5]:
df=pd.read_csv("../data/StudentsPerformance.csv")

In [7]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [8]:
categorical_cols = df.select_dtypes(include="str").columns
categorical_cols

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course'],
      dtype='str')

In [9]:
for col in categorical_cols:
    print(f"\n{col}")
    print(df[col].unique())

gender
<StringArray>
['female', 'male']
Length: 2, dtype: str

race/ethnicity
<StringArray>
['group B', 'group C', 'group A', 'group D', 'group E']
Length: 5, dtype: str

parental level of education
<StringArray>
[ 'bachelor's degree',       'some college',    'master's degree',
 'associate's degree',        'high school',   'some high school']
Length: 6, dtype: str

lunch
<StringArray>
['standard', 'free/reduced']
Length: 2, dtype: str

test preparation course
<StringArray>
['none', 'completed']
Length: 2, dtype: str

In [10]:
df_encoded = pd.get_dummies( df, 
   columns=categorical_cols, 
   dtype=int
)

In [11]:
df_encoded

,math score,reading score,writing score,gender_female,gender_male,race/ethnicity_group A,race/ethnicity_group B,race/ethnicity_group C,race/ethnicity_group D,race/ethnicity_group E,parental level of education_associate's degree,parental level of education_bachelor's degree,parental level of education_high school,parental level of education_master's degree,parental level of education_some college,parental level of education_some high school,lunch_free/reduced,lunch_standard,test preparation course_completed,test preparation course_none
0,72,72,74,1,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,1
1,69,90,88,1,0,0,0,1,0,0,0,0,0,0,1,0,0,1,1,0
2,90,95,93,1,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,1
3,47,57,44,0,1,1,0,0,0,0,1,0,0,0,0,0,1,0,0,1
4,76,78,75,0,1,0,0,1,0,0,0,0,0,0,1,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,88,99,95,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,1,0
996,62,55,55,0,1,0,0,1,0,0,0,0,1,0,0,0,1,0,0,1
997,59,71,65,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,1,0
998,68,78,77,1,0,0,0,0,1,0,0,0,0,0,1,0,0,1,1,0
999,77,86,86,1,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,1

In [12]:
df_encoded.shape

(1000, 20)

In [12]:
df_encoded.columns

Index(['math score', 'reading score', 'writing score', 'gender_female',
       'gender_male', 'race/ethnicity_group A', 'race/ethnicity_group B',
       'race/ethnicity_group C', 'race/ethnicity_group D',
       'race/ethnicity_group E',
       'parental level of education_associate's degree',
       'parental level of education_bachelor's degree',
       'parental level of education_high school',
       'parental level of education_master's degree',
       'parental level of education_some college',
       'parental level of education_some high school', 'lunch_free/reduced',
       'lunch_standard', 'test preparation course_completed',
       'test preparation course_none'],
      dtype='str')

In [13]:
df_encoded.dtypes

math score                                        int64
reading score                                     int64
writing score                                     int64
gender_female                                     int64
gender_male                                       int64
race/ethnicity_group A                            int64
race/ethnicity_group B                            int64
race/ethnicity_group C                            int64
race/ethnicity_group D                            int64
race/ethnicity_group E                            int64
parental level of education_associate's degree    int64
parental level of education_bachelor's degree     int64
parental level of education_high school           int64
parental level of education_master's degree       int64
parental level of education_some college          int64
parental level of education_some high school      int64
lunch_free/reduced                                int64
lunch_standard                                    int64
test preparation course_completed                 int64
test preparation course_none                      int64
dtype: object

In [14]:
numeric_cols = df.select_dtypes(include="number").columns
numeric_cols

Index(['math score', 'reading score', 'writing score'], dtype='str')

In [15]:
scaler = StandardScaler()

In [16]:
df_encoded[numeric_cols] = scaler.fit_transform(df_encoded[numeric_cols])

In [17]:
df_encoded[numeric_cols].head()

   math score  reading score  writing score
0    0.390024       0.193999       0.391492
1    0.192076       1.427476       1.313269
2    1.577711       1.770109       1.642475
3   -1.259543      -0.833899      -1.583744
4    0.653954       0.605158       0.457333

In [18]:
df_encoded[numeric_cols].mean()

math score       8.704149e-17
reading score    2.167155e-16
writing score   -1.350031e-16
dtype: float64

In [19]:
df_encoded[numeric_cols].std()

math score       1.0005
reading score    1.0005
writing score    1.0005
dtype: float64

In [20]:
df_encoded["average_score"] = df[
    ["math score", "reading score", "writing score"]
].mean(axis=1)

In [22]:
df_encoded[[
    "math score",
    "reading score",
    "writing score",
    "average_score"
]]

     math score  reading score  writing score  average_score
0      0.390024       0.193999       0.391492      72.666667
1      0.192076       1.427476       1.313269      82.333333
2      1.577711       1.770109       1.642475      92.666667
3     -1.259543      -0.833899      -1.583744      49.333333
4      0.653954       0.605158       0.457333      76.333333
..          ...            ...            ...            ...
995    1.445746       2.044215       1.774157      94.000000
996   -0.269803      -0.970952      -0.859491      57.333333
997   -0.467751       0.125472      -0.201079      65.000000
998    0.126093       0.605158       0.589015      74.333333
999    0.719937       1.153370       1.181586      83.000000

[1000 rows x 4 columns]

La variable average_score représente la performance académique globale de chaque élève en calculant la moyenne de ses scores en mathématiques, lecture et écriture. Elle permet de synthétiser les trois performances individuelles en un indicateur unique, tout en restant facilement interprétable sur une échelle de 0 à 100.

In [23]:
df_encoded.shape

(1000, 21)

In [25]:
df_encoded.isnull().sum().sum()

np.int64(0)

In [26]:
df_encoded.dtypes

math score                                        float64
reading score                                     float64
writing score                                     float64
gender_female                                       int64
gender_male                                         int64
race/ethnicity_group A                              int64
race/ethnicity_group B                              int64
race/ethnicity_group C                              int64
race/ethnicity_group D                              int64
race/ethnicity_group E                              int64
parental level of education_associate's degree      int64
parental level of education_bachelor's degree       int64
parental level of education_high school             int64
parental level of education_master's degree         int64
parental level of education_some college            int64
parental level of education_some high school        int64
lunch_free/reduced                                  int64
lunch_standard                                      int64
test preparation course_completed                   int64
test preparation course_none                        int64
average_score                                     float64
dtype: object

In [27]:
df_encoded.duplicated().sum()

np.int64(0)

In [28]:
df_encoded.to_csv("../data/engineered_data.csv", index=False)